#define MAINPREFIX b
#define PREFIX kmns

#define MAJOR 1
#define MINOR 2
#define PATCHLVL 0
#define BUILD 0

#define VERSION MAJOR.MINOR.PATCHLVL.BUILD
#define VERSION_AR MAJOR,MINOR,PATCHLVL,BUILD

#define REQUIRED_VERSION 0.1
